---
- name: Remove apache2
  apt: name=apache2 state=absent

- name: Add key for passenger
  apt_key: url=http://keyserver.ubuntu.com id=AC40B2F7 state=present

- name: Apt via https
  apt: name=apt-transport-https state=present
  
- name: Apt add passenger to list  
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger precise main' state=present update_cache=yes
    
- name: Install nginx
  action: apt pkg={{ item }} state=installed
  with_items:
   - nginx-extras 
   - passenger